### ISSUE TITLE
Add Transparent Fill

### ISSUE THREAD

**Issue by tjlanza** [Voldemalort/token-factions#3]
Not all tokens are designed completely obscure the background underneath them. This module uses a solid fill inside the color ring. Providing an option to make that fill translucent or transparent would be a great improvement.

**Comment by Voldemalort** [comment]
Is the desire to just have a frame ring in those cases? If so that becomes a bit trickier as you have to choose if the ring goes under or over. IF there are too many per-token dials and knobs and you have to adjust them to get it right per token I think the module becomes less attractive to general use. This may be one of the cases where my opinionated approach deviates from what you'd prefer.

**Comment by tjlanza** [comment]
Yeah, the idea would be just the ring. I would think that filled would always be under the token and unfilled/ring would always be over.

**Comment by Voldemalort** [comment]
Currently both are generated under, but an additional ring can be selected to generate over. This is so that baseless tokens, such as humanoids seen from above, won't have the ring on top of an outstretched arm or weapon.

**Comment by Voldemalort** [comment]
working on this

**Comment by Voldemalort** [comment]
just released
